{% set name = "scikit-fuzzy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ab12424d847ede1bc79670d8058167be7c8dd660b00756e9b844817ceb1e12e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    # Pure python
  host:
    - python
    - pip
    - numpy >=1.6
  run:
    - python
    - numpy >=1.6
    - scipy >=0.9
    - networkx >=1.9
    - matplotlib >=1.5

test:
  imports:
    - skfuzzy
    - skfuzzy.control

about:
  home: http://github.com/scikit-fuzzy/scikit-fuzzy

  license: BSD
  license_family: BSD
  license_file: LICENSE.txt

  summary: 'Fuzzy logic toolbox for Python.'
  description: |
    This package implements many useful tools for projects involving fuzzy logic,
    also known as grey logic. It is pure Python and depends only on NumPy, SciPy, and
    NetworkX.  There are many basic fuzzy logic functions in the base namespace, as
    well as a Pythonic, object-oriented system for fuzzy control systems in the
    skfuzzy.control submodule.
  doc_url: http://scikit-fuzzy.readthedocs.io/
  dev_url: https://github.com/scikit-fuzzy/scikit-fuzzy

extra:
  recipe-maintainers:
    - JDWarner
