{% set name = "scikit-fuzzy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ee5340523aa7635ca568b9d8029c7738d05f9ea550fc89d4054b4cb50f34e7f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    # Pure python
  host:
    - python >=3.8
    - pip
    - setuptools
    - numpy >=1.6
  run:
    - python >=3.8
    - numpy >=1.6
    - scipy >=0.9
    - networkx >=1.9
    - matplotlib-base >=1.5

test:
  imports:
    - skfuzzy
    - skfuzzy.control

about:
  home: http://github.com/scikit-fuzzy/scikit-fuzzy

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

  summary: 'Fuzzy logic toolbox for Python.'
  description: |
    This package implements many useful tools for projects involving fuzzy logic,
    also known as grey logic. It is pure Python and depends only on NumPy, SciPy, and
    NetworkX.  There are many basic fuzzy logic functions in the base namespace, as
    well as a Pythonic, object-oriented system for fuzzy control systems in the
    skfuzzy.control submodule.
  doc_url: http://scikit-fuzzy.readthedocs.io/
  dev_url: https://github.com/scikit-fuzzy/scikit-fuzzy

extra:
  recipe-maintainers:
    - JDWarner
