travis:
  secure:
    BINSTAR_TOKEN: nOD33mj66O3lP+ZyyByAzPPUW+E5OLWKnYJxlpmVMwvEvX3PHAx6Ey6vv2Fndg9aWrMVjhXD62Qm4Z/iKrZFLHFSfu59jsqg7EDuTIoQLBH/3JQkD0Dq5Dmsa+cs3eubFreYftONfA2zY7Vwu0aMFLcoPcVoLaVPSltokXsMDJ6CmS0JlI6EdgoSz4XJdUZsh5pWW3/BIpdB1SJXF/QVoTlxpk75q8j0+oua6OZlDWnOrSp8xDJbjH7yJAvYNYSrg3WChtjCNxFPZW0+7RpQmY7GAifZpfL2rWoTP7DMR3mdtNW7NElybctmOG9L0eDBi8OJ59YRwxj/0XjwToL9CoXjNxGieFREsL/01S0C3zl3CgW56wl5V6tTR2m37i0AcLt0/3kmaUPa4+cw+TURWCypdj7vTHxm7eStGkawaDzowfBoM7Ftq2qXerACD/vQn3HaK2UiMepzGRVQcftmHvkYlLRSv/4iX9RnL6xgpQLZgjslci0wBR8U3BtUATJvWGS5VQl4lr2AIKiMC/nimGwsEViRuy7OO0dgLF4FbWrhrQazrBltumDsJHAGE2DTJBjAuy9gPPkCnAAKPcNNcbXb5ohHaReR8X8L6JvdMLCbrqOkvJRVMQey3jX7xsm7F7ZbbpDqc4dPHy9vfEDnVvQupSDSOCjz3f9yJoNkroE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
